export const handleError = async (error) => {
  console.error(error)
}
